# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 The Foundation for Public Code <info@publiccode.net>

title: Process code

remote_theme: publiccodenet/staging-jekyll-theme
include:
  - "index.md"

toc: false

#baseurl: /
